# Generated by Django 4.0.2 on 2022-02-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argonaute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sailors',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sailors',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
