# Generated by Django 4.0.2 on 2022-02-15 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('argonaute', '0002_alter_sailors_height_alter_sailors_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sailors',
            old_name='price',
            new_name='salary',
        ),
    ]
